from .View_Nguoidung import NguoiDungForm
from .View_Sidebar import Sidebar
from .View_Studio import StudioForm
from .View_DuAn import DuAnForm
from .View_Phongban import PhongBanForm
from .View_DuAn import DuAnForm
from .View_NhanVien import Nhan_vien_form
from .View_CongViec import CongViecForm
from .View_dang_nhap import View_dang_nhap
from .View_dang_ky import View_dang_ky